import {
  createCalendarCategory,
  getAllCalendarCategories,
} from "@/provider/features/calendar-categories/calendar-categories.slice";
import {
  createCalendarTask,
  getAllCalendarTasks,
  toggleCalendarTaskStatus,
} from "@/provider/features/calendar-tasks/calendar-tasks.slice";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

export default function useCalendarModal(show, selectedCampaign) {
  const dispatch = useDispatch();

  // Redux state
  const {
    tasks,
    createTask: createTaskState,
    updateTask: updateTaskState,
    toggleTask: toggleTaskState,
    deleteTask: deleteTaskState,
    getAllTasks: getAllTasksState,
  } = useSelector((state) => state.calendarTasks);

  const {
    categories,
    createCategory: createCategoryState,
    getAllCategories: getAllCategoriesState,
  } = useSelector((state) => state.calendarCategories);

  // Local state
  const [selectedDate, setSelectedDate] = useState(new Date().getDate());
  const [currentMonth, setCurrentMonth] = useState({
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
  });
  const [newTaskText, setNewTaskText] = useState("");
  const [selectedTag, setSelectedTag] = useState("");
  const [showAddTag, setShowAddTag] = useState(false);
  const [newTagName, setNewTagName] = useState("");
  const [newTagColor, setNewTagColor] = useState("bg-gray-100 text-gray-800");

  // Month names
  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  // Default categories (auto-generated tags)
  const defaultCategories = [
    { label: "Campaign Deadline", color: "bg-red-500 text-white", isDefault: true },
    { label: "1st Draft Deadline", color: "bg-orange-500 text-white", isDefault: true },
  ];

  // Color options for new tags
  const colorOptions = [
    "bg-blue-500 text-white",
    "bg-green-500 text-white",
    "bg-purple-500 text-white",
    "bg-yellow-500 text-white",
    "bg-teal-500 text-white",
    "bg-pink-500 text-white",
  ];

  // Load data when modal opens
  useEffect(() => {
    if (show && selectedCampaign?.id) {
      dispatch(getAllCalendarTasks());
      dispatch(getAllCalendarCategories());
    }
  }, [show, selectedCampaign?.id, dispatch]);

  // Transform tasks for calendar display
  const calendarTasks = tasks.reduce((acc, task) => {
    // Handle date string directly to avoid timezone issues
    let day;
    if (typeof task.task_date === "string") {
      // Extract day from YYYY-MM-DD format
      day = parseInt(task.task_date.split("-")[2]);
    } else {
      // Fallback for Date objects
      const taskDate = new Date(task.task_date);
      day = taskDate.getDate();
    }

    if (!acc[day]) {
      acc[day] = [];
    }

    acc[day].push({
      id: task.id,
      text: task.task_text,
      completed: task.status === "completed",
      tag: { label: task.tag_label, value: task.tag_color },
      isAutoGenerated: task.is_auto_generated,
    });

    return acc;
  }, {});

  // Combine default and custom categories, removing duplicates
  const allCategories = [
    ...defaultCategories,
    ...categories.filter(
      (cat) => !defaultCategories.some((defaultCat) => defaultCat.label === cat.label)
    ),
  ];

  // Transform categories for dropdown
  const categoryOptions = allCategories.map((category) => ({
    label: category.label,
    value: { label: category.label, value: category.color },
  }));

  // Get dot indicators for calendar dates
  const getDateIndicators = (day) => {
    const dayTasks = calendarTasks[day] || [];
    const hasDeadline = dayTasks.some((task) => task.tag.label === "Campaign Deadline");
    const hasDraft = dayTasks.some((task) => task.tag.label === "1st Draft Deadline");
    const hasOther = dayTasks.some(
      (task) => !["Campaign Deadline", "1st Draft Deadline"].includes(task.tag.label)
    );

    return { hasDeadline, hasDraft, hasOther };
  };

  // Handle date click
  const handleDateClick = (day) => {
    setSelectedDate(day);
  };

  // Navigate month
  const navigateMonth = (direction) => {
    setCurrentMonth((prev) => {
      const newMonth = direction === "next" ? prev.month + 1 : prev.month - 1;
      if (newMonth > 12) return { month: 1, year: prev.year + 1 };
      if (newMonth < 1) return { month: 12, year: prev.year - 1 };
      return { ...prev, month: newMonth };
    });
  };

  // Add task
  const addTask = async () => {
    if (newTaskText.trim() && selectedTag && selectedCampaign?.id) {
      // Create date string in YYYY-MM-DD format to avoid timezone issues
      const year = currentMonth.year;
      const month = String(currentMonth.month).padStart(2, "0");
      const day = String(selectedDate).padStart(2, "0");
      const taskDateString = `${year}-${month}-${day}`;

      await dispatch(
        createCalendarTask({
          campaign_id: selectedCampaign.id,
          task_text: newTaskText,
          task_date: taskDateString,
          tag_label: selectedTag.label,
          tag_color: selectedTag.value.value, // Extract the color string from the value object
          is_auto_generated: false,
        })
      ).unwrap();

      setNewTaskText("");
      setSelectedTag("");
    }
  };

  // Toggle task completion
  const toggleTask = async (taskId) => {
    await dispatch(toggleCalendarTaskStatus({ taskId })).unwrap();
  };

  // Add color tag
  const addColorTag = async () => {
    if (newTagName.trim() && selectedCampaign?.id) {
      // Check for duplicates (both in default and custom categories)
      const isDuplicate = allCategories.some(
        (cat) => cat.label.toLowerCase() === newTagName.trim().toLowerCase()
      );

      if (isDuplicate) {
        alert(`Category "${newTagName.trim()}" already exists. Please choose a different name.`);
        return;
      }

      await dispatch(
        createCalendarCategory({
          campaign_id: selectedCampaign.id,
          label: newTagName.trim(),
          color: newTagColor,
        })
      ).unwrap();

      setNewTagName("");
      setShowAddTag(false);
    }
  };

  // Get tag color
  const getTagColor = (tagName) => {
    const tag = allCategories.find((t) => t.label === tagName);
    return tag ? tag.color : "bg-gray-100 text-gray-800";
  };

  // Handle new task text change
  const handleNewTaskTextChange = (e) => {
    setNewTaskText(e.target.value);
  };

  // Handle new tag name change
  const handleNewTagNameChange = (e) => {
    setNewTagName(e.target.value);
  };

  // Handle new tag color change
  const handleNewTagColorChange = (color) => {
    setNewTagColor(color);
  };

  // Handle tag selection
  const handleTagSelection = (value) => {
    setSelectedTag(value);
  };

  // Toggle add tag form
  const toggleAddTag = () => {
    setShowAddTag(true);
  };

  // Cancel add tag
  const cancelAddTag = () => {
    setShowAddTag(false);
    setNewTagName("");
  };

  return {
    // State
    selectedDate,
    currentMonth,
    newTaskText,
    selectedTag,
    showAddTag,
    newTagName,
    newTagColor,
    calendarTasks,
    categoryOptions,
    allCategories,
    monthNames,
    colorOptions,

    // Redux states
    createTaskState,
    updateTaskState,
    toggleTaskState,
    deleteTaskState,
    getAllTasksState,
    createCategoryState,
    getAllCategoriesState,

    // Actions
    handleDateClick,
    navigateMonth,
    addTask,
    toggleTask,
    addColorTag,
    getTagColor,
    getDateIndicators,
    handleNewTaskTextChange,
    handleNewTagNameChange,
    handleNewTagColorChange,
    handleTagSelection,
    toggleAddTag,
    cancelAddTag,
  };
}
