import {
  createCalendarCategory,
  getAllCalendarCategories,
  deleteCalendarCategory,
} from "@/provider/features/calendar-categories/calendar-categories.slice";
import {
  createCalendarTask,
  getAllCalendarTasks,
  getCreatorTasksByMonth,
  getTasksByCampaign,
  toggleCalendarTaskStatus,
} from "@/provider/features/calendar-tasks/calendar-tasks.slice";
import { useEffect, useState, useMemo } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getUser, isCreatorMode } from "@/common/utils/users.util";

export default function useCalendarModal(show, selectedCampaign) {
  const dispatch = useDispatch();
  const creatorMode = isCreatorMode();
  const user = getUser();

  // Redux state
  const {
    tasks,
    createTask: createTaskState,
    updateTask: updateTaskState,
    toggleTask: toggleTaskState,
    deleteTask: deleteTaskState,
    getAllTasks: getAllTasksState,
  } = useSelector((state) => state.calendarTasks);

  const {
    categories,
    createCategory: createCategoryState,
    getAllCategories: getAllCategoriesState,
  } = useSelector((state) => state.calendarCategories);

  // Local state
  const [selectedDate, setSelectedDate] = useState(new Date().getDate());
  const [currentMonth, setCurrentMonth] = useState({
    month: new Date().getMonth() + 1,
    year: new Date().getFullYear(),
  });
  const [newTaskText, setNewTaskText] = useState("");
  const [selectedTag, setSelectedTag] = useState("");
  const [showAddTag, setShowAddTag] = useState(false);
  const [newTagName, setNewTagName] = useState("");
  const [newTagColor, setNewTagColor] = useState("bg-gray-100 text-gray-800");
  const [showDeleteConfirmation, setShowDeleteConfirmation] = useState(false);
  const [categoryToDelete, setCategoryToDelete] = useState(null);

  // Month names
  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  // Default categories (auto-generated tags)
  const defaultCategories = [
    { label: "Campaign Deadline", color: "bg-red-500 text-white", isDefault: true },
    { label: "1st Draft Deadline", color: "bg-orange-500 text-white", isDefault: true },
  ];

  // Color options for new tags
  const colorOptions = [
    "bg-blue-500 text-white",
    "bg-green-500 text-white",
    "bg-purple-500 text-white",
    "bg-yellow-500 text-white",
    "bg-teal-500 text-white",
    "bg-pink-500 text-white",
  ];

  // Load data when modal opens
  useEffect(() => {
    if (show) {
      // Load categories for both
      if (selectedCampaign?.id || creatorMode) {
        dispatch(getAllCalendarCategories());
      }
    }
  }, [show, selectedCampaign?.id, dispatch, creatorMode]);

  // Load tasks when modal opens, campaign changes, or month changes
  useEffect(() => {
    if (show) {
      // For creators: Load all tasks from all campaigns for the current month
      if (creatorMode) {
        dispatch(getCreatorTasksByMonth({ month: currentMonth.month, year: currentMonth.year }));
      }
      // For brands: Load tasks for the selected campaign ONLY
      else if (selectedCampaign?.id) {
        dispatch(getTasksByCampaign(selectedCampaign.id));
      }
    }
  }, [show, selectedCampaign?.id, dispatch, creatorMode, currentMonth.month, currentMonth.year]);

  // Transform tasks for calendar display and add deadlines
  const calendarTasks = useMemo(() => {
    // Start with tasks from the database
    const tasksMap = tasks.reduce((acc, task) => {
      let day;
      if (typeof task.task_date === "string") {
        day = parseInt(task.task_date.split("-")[2]);
      } else {
        const taskDate = new Date(task.task_date);
        day = taskDate.getDate();
      }

      if (!acc[day]) {
        acc[day] = [];
      }

      acc[day].push({
        id: task.id,
        text: task.task_text,
        completed: task.status === "completed",
        tag: { label: task.tag_label, value: task.tag_color },
        isAutoGenerated: task.is_auto_generated,
      });

      return acc;
    }, {});

    // Check if deadlines already exist in tasks
    const existingDeadlines = {
      campaignDeadline: tasks.find((task) => task.tag_label === "Campaign Deadline"),
      firstDraftDeadline: tasks.find((task) => task.tag_label === "1st Draft Deadline"),
    };

    // Add campaign deadlines from selectedCampaign (only if they don't already exist as tasks)
    if (selectedCampaign) {
      const campaignDeadline =
        selectedCampaign.application_deadline ||
        selectedCampaign.campaign?.application_deadline ||
        selectedCampaign.contract?.completionDeadline;

      const firstDraftDeadline = selectedCampaign.contract?.firstDraftDeadline;

      // Helper function to add deadline task
      const addDeadlineTask = (deadline, label, color) => {
        if (!deadline) return;

        if (label === "Campaign Deadline" && existingDeadlines.campaignDeadline) return;
        if (label === "1st Draft Deadline" && existingDeadlines.firstDraftDeadline) return;

        try {
          const deadlineDate = new Date(deadline);
          if (isNaN(deadlineDate.getTime())) return;

          const deadlineMonth = deadlineDate.getMonth() + 1;
          const deadlineYear = deadlineDate.getFullYear();
          const deadlineDay = deadlineDate.getDate();

          if (
            deadlineMonth === currentMonth.month &&
            deadlineYear === currentMonth.year
          ) {
            if (!tasksMap[deadlineDay]) {
              tasksMap[deadlineDay] = [];
            }

            const exists = tasksMap[deadlineDay].some(
              (task) => task.tag.label === label && task.isAutoGenerated
            );

            if (!exists) {
              tasksMap[deadlineDay].push({
                id: `auto-${label}-${deadlineDay}`,
                text: label,
                completed: false,
                tag: { label, value: color },
                isAutoGenerated: true,
              });
            }
          }
        } catch (error) {
          // Invalid date, skip
        }
      };

      addDeadlineTask(campaignDeadline, "Campaign Deadline", "bg-red-500 text-white");
      addDeadlineTask(firstDraftDeadline, "1st Draft Deadline", "bg-orange-500 text-white");
    }

    return tasksMap;
  }, [tasks, selectedCampaign, currentMonth.month, currentMonth.year]);

  // Combine default and custom categories, removing duplicates
  const allCategories = [
    ...defaultCategories,
    ...categories.filter(
      (cat) => !defaultCategories.some((defaultCat) => defaultCat.label === cat.label)
    ),
  ];

  // Transform categories for dropdown (only custom categories, not default ones)
  const categoryOptions = allCategories
    .filter((category) => !category.isDefault)
    .map((category) => ({
      label: category.label,
      value: { label: category.label, value: category.color },
    }));

  // Get dot indicators for calendar dates
  const getDateIndicators = (day) => {
    const dayTasks = calendarTasks[day] || [];
    const hasDeadline = dayTasks.some((task) => task.tag.label === "Campaign Deadline");
    const hasDraft = dayTasks.some((task) => task.tag.label === "1st Draft Deadline");
    const hasOther = dayTasks.some(
      (task) => !["Campaign Deadline", "1st Draft Deadline"].includes(task.tag.label)
    );

    return { hasDeadline, hasDraft, hasOther };
  };

  // Handle date click
  const handleDateClick = (day) => {
    setSelectedDate(day);
  };

  // Navigate month
  const navigateMonth = (direction) => {
    setCurrentMonth((prev) => {
      const newMonth = direction === "next" ? prev.month + 1 : prev.month - 1;
      let newYear = prev.year;
      let finalMonth = newMonth;

      if (newMonth > 12) {
        finalMonth = 1;
        newYear = prev.year + 1;
      } else if (newMonth < 1) {
        finalMonth = 12;
        newYear = prev.year - 1;
      }

      return { month: finalMonth, year: newYear };
    });
  };

  // Add task
  const addTask = async () => {
    if (newTaskText.trim() && selectedTag && selectedCampaign?.id) {
      // Create date string in YYYY-MM-DD format to avoid timezone issues
      const year = currentMonth.year;
      const month = String(currentMonth.month).padStart(2, "0");
      const day = String(selectedDate).padStart(2, "0");
      const taskDateString = `${year}-${month}-${day}`;

      try {
        await dispatch(
          createCalendarTask({
            campaign_id: selectedCampaign.id,
            task_text: newTaskText,
            task_date: taskDateString,
            tag_label: selectedTag.label,
            tag_color: selectedTag.value.value, // Extract the color string from the value object
            is_auto_generated: false,
          })
        ).unwrap();

        setNewTaskText("");
        setSelectedTag("");

        // Refresh tasks after creating
        if (creatorMode) {
          dispatch(getCreatorTasksByMonth({ month: currentMonth.month, year: currentMonth.year }));
        } else if (selectedCampaign?.id) {
          dispatch(getTasksByCampaign(selectedCampaign.id));
        }
      } catch (error) {
        // Error is handled by Redux state
        console.error("Failed to create task:", error);
      }
    }
  };

  // Toggle task completion
  const toggleTask = async (taskId) => {
    await dispatch(toggleCalendarTaskStatus({ taskId })).unwrap();
  };

  // Add color tag
  const addColorTag = async () => {
    if (newTagName.trim() && selectedCampaign?.id) {
      // Check for duplicates (both in default and custom categories)
      const isDuplicate = allCategories.some(
        (cat) => cat.label.toLowerCase() === newTagName.trim().toLowerCase()
      );

      if (isDuplicate) {
        alert(`Category "${newTagName.trim()}" already exists. Please choose a different name.`);
        return;
      }

      await dispatch(
        createCalendarCategory({
          campaign_id: selectedCampaign.id,
          label: newTagName.trim(),
          color: newTagColor,
        })
      ).unwrap();

      setNewTagName("");
      setShowAddTag(false);
    }
  };

  // Get tag color
  const getTagColor = (tagName) => {
    const tag = allCategories.find((t) => t.label === tagName);
    return tag ? tag.color : "bg-gray-100 text-gray-800";
  };

  // Handle new task text change
  const handleNewTaskTextChange = (e) => {
    setNewTaskText(e.target.value);
  };

  // Handle new tag name change
  const handleNewTagNameChange = (e) => {
    setNewTagName(e.target.value);
  };

  // Handle new tag color change
  const handleNewTagColorChange = (color) => {
    setNewTagColor(color);
  };

  // Handle tag selection
  const handleTagSelection = (value) => {
    setSelectedTag(value);
  };

  // Toggle add tag form
  const toggleAddTag = () => {
    setShowAddTag(true);
  };

  // Cancel add tag
  const cancelAddTag = () => {
    setShowAddTag(false);
    setNewTagName("");
  };

  // Handle delete category click
  const handleDeleteCategoryClick = (categoryId, categoryLabel) => {
    setCategoryToDelete({ id: categoryId, label: categoryLabel });
    setShowDeleteConfirmation(true);
  };

  // Confirm delete category
  const handleConfirmDelete = async () => {
    if (!categoryToDelete?.id) return;

    try {
      await dispatch(deleteCalendarCategory(categoryToDelete.id)).unwrap();
      dispatch(getAllCalendarCategories());
      setShowDeleteConfirmation(false);
      setCategoryToDelete(null);
    } catch (error) {
      const errorMessage =
        error?.message || error?.payload?.message || "Unknown error";
      alert(`Failed to delete category: ${errorMessage}`);
    }
  };

  // Cancel delete
  const handleCancelDelete = () => {
    setShowDeleteConfirmation(false);
    setCategoryToDelete(null);
  };

  return {
    // State
    selectedDate,
    currentMonth,
    newTaskText,
    selectedTag,
    showAddTag,
    newTagName,
    newTagColor,
    calendarTasks,
    categoryOptions,
    allCategories,
    monthNames,
    colorOptions,

    // Redux states
    createTaskState,
    updateTaskState,
    toggleTaskState,
    deleteTaskState,
    getAllTasksState,
    createCategoryState,
    getAllCategoriesState,

    // Actions
    handleDateClick,
    navigateMonth,
    addTask,
    toggleTask,
    addColorTag,
    getTagColor,
    getDateIndicators,
    handleNewTaskTextChange,
    handleNewTagNameChange,
    handleNewTagColorChange,
    handleTagSelection,
    toggleAddTag,
    cancelAddTag,
    handleDeleteCategoryClick,
    showDeleteConfirmation,
    categoryToDelete,
    handleConfirmDelete,
    handleCancelDelete,
  };
}
