export default {
  title: "Privacy Policy",
  lastUpdated: "June 4, 2026",
  sections: [
    {
      heading: "Introduction",
      paragraphs: [
        "CleerCut provides a platform for Clients and Creators to collaborate. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you access or use our website, applications, and services (collectively, the Services).",
        "By using CleerCut, you agree to the practices described in this Privacy Policy. CleerCut does not knowingly collect or process data from individuals under the age of eighteen.",
      ],
    },
    {
      heading: "1. Information We Collect",
      paragraphs: [
        "A. Information You Provide Directly",
        "When you create an account or use the Services, we may collect:",
        "• Name",
        "• Email address",
        "• Phone number",
        "• Username and password",
        "• Social media handles",
        "• Profile details",
        "• Self-reported demographic information, including age range, gender, location, and ethnicity",
        "• Content you upload or submit",
        "• Messages sent through the platform",
        "Demographic information is voluntarily provided by users for discovery and collaboration matching purposes.",
        "B. Social Media and API Data",
        "When Creators connect social media accounts, they authorize CleerCut to access certain account data through third party API providers, including Phyllo. This may include:",
        "• Public profile information",
        "• Follower counts",
        "• Engagement metrics",
        "• Content performance metrics",
        "• Account level analytics",
        "CleerCut stores authentication tokens necessary to retrieve authorized data. Creators may revoke access at any time through the relevant platform settings. CleerCut does not control and is not responsible for changes made by third party platforms or API providers.",
        "C. Payment Information",
        "Payments are processed through third party payment providers, including Stripe Connect. CleerCut does not store full credit card numbers, bank account numbers, government identification numbers, or tax identification numbers. Identity verification and tax documentation are handled directly by the payment provider.",
        "D. Automatically Collected Information",
        "When you access the Services, we may collect:",
        "• IP address",
        "• Device type",
        "• Browser type",
        "• Operating system",
        "• Usage timestamps",
        "• Pages visited",
        "CleerCut does not use behavioral advertising tools such as retargeting pixels.",
      ],
    },
    {
      heading: "2. How We Use Information",
      paragraphs: [
        "We use collected information to:",
        "• Create and manage user accounts",
        "• Facilitate collaborations between Clients and Creators",
        "• Process payments through third party providers",
        "• Improve platform functionality and performance",
        "• Provide customer support",
        "• Detect fraud and prevent misuse",
        "• Comply with legal obligations",
        "CleerCut does not sell personal information and does not share personal information for cross-contextual behavioral advertising.",
      ],
    },
    {
      heading: "3. How We Share Information",
      paragraphs: [
        "With Service Providers",
        "Including cloud hosting providers, API partners such as Phyllo, and payment processors such as Stripe.",
        "With Other Users",
        "Profile information and campaign-related details may be visible to other users for collaboration purposes. Private metrics or personal demographic data are not publicly displayed.",
        "For Legal Reasons",
        "If required by law, subpoena, court order, or to protect the rights and safety of CleerCut or its users.",
        "Business Transfers",
        "In connection with a merger, acquisition, restructuring, or sale of assets.",
      ],
    },
    {
      heading: "4. Data Retention",
      paragraphs: [
        "Account data is retained while your account remains active. If you delete your account:",
        "• Profile information will be removed from public view",
        "• Financial transaction records may be retained as required by law",
        "• Backup copies may be retained for a limited period",
        "CleerCut retains information only as long as necessary to provide Services and comply with legal obligations.",
      ],
    },
    {
      heading: "5. Your Rights",
      paragraphs: [
        "Depending on your jurisdiction, you may have the right to:",
        "• Access the personal information we hold about you",
        "• Correct inaccurate information",
        "• Request deletion of personal information",
        "• Request information about how your data is used",
        "• Opt out of marketing communications",
        "• Request that we limit certain data processing",
        "CleerCut does not sell personal information. California residents may exercise rights under the California Consumer Privacy Act and California Privacy Rights Act, including the right to know, delete, correct, and opt out of the sale or sharing of personal information. We will not discriminate against users for exercising privacy rights.",
        "To exercise your rights, contact: hello@cleercut.com",
      ],
    },
    {
      heading: "6. International Data Transfers",
      paragraphs: [
        "CleerCut may process and store data in the United States and other countries. By using the Services, you acknowledge that your information may be transferred to jurisdictions with different data protection laws. CleerCut takes reasonable measures to safeguard international data transfers in accordance with applicable law.",
      ],
    },
    {
      heading: "7. Data Security",
      paragraphs: [
        "We implement administrative, technical, and organizational safeguards to protect personal information. However, no system can guarantee absolute security. In the event of a data breach, CleerCut will notify affected users as required by applicable law.",
      ],
    },
    {
      heading: "8. Cookies and Tracking",
      paragraphs: [
        "CleerCut uses cookies for:",
        "• Account authentication",
        "• Session management",
        "• Platform functionality",
        "CleerCut does not use cookies for behavioral advertising. You may control cookies through your browser settings.",
      ],
    },
    {
      heading: "9. Changes to This Policy",
      paragraphs: [
        "CleerCut may update this Privacy Policy periodically. Changes will be posted with a revised effective date. Continued use of the Services constitutes acceptance of the updated policy.",
      ],
    },
    {
      heading: "10. Contact Information",
      paragraphs: [
        "For questions regarding this Privacy Policy or data requests, contact: hello@cleercut.com",
      ],
    },
  ],
};
