import { NOTIFICATION_TYPE } from "@/common/constants/notification.constant";

export const NOTIFICATION_SECTION = {
  ACTION_REQUIRED: "ACTION_REQUIRED",
  EXECUTION_UPDATES: "EXECUTION_UPDATES",
  APPLICATIONS: "APPLICATIONS",
  OTHER_UPDATES: "OTHER_UPDATES",
};

export function getNotificationSection(type) {
  // Action Required - blocking items
  if (
    type === NOTIFICATION_TYPE.ESCROW_FUNDING_FAILED ||
    type === NOTIFICATION_TYPE.REFUND_CHARGEBACK ||
    type === NOTIFICATION_TYPE.DELIVERABLE_OVERDUE ||
    type === NOTIFICATION_TYPE.DRAFT_WAITING_REVIEW ||
    type === NOTIFICATION_TYPE.REVISION_WAITING_REVIEW ||
    type === NOTIFICATION_TYPE.PUBLISH_PROOF_WAITING_VERIFICATION ||
    type === NOTIFICATION_TYPE.READY_TO_COMPLETE ||
    type === NOTIFICATION_TYPE.APPLICATION_DEADLINE_APPROACHING
  ) {
    return NOTIFICATION_SECTION.ACTION_REQUIRED;
  }

  // Execution Updates - in-progress activity
  if (
    type === NOTIFICATION_TYPE.DELIVERABLE_SUBMITTED ||
    type === NOTIFICATION_TYPE.DELIVERABLE_APPROVED ||
    type === NOTIFICATION_TYPE.DELIVERABLE_DUE_SOON ||
    type === NOTIFICATION_TYPE.DEADLINE_EXTENDED ||
    type === NOTIFICATION_TYPE.CREATOR_MARKED_DELAYED ||
    type === NOTIFICATION_TYPE.CREATOR_REMOVED ||
    type === NOTIFICATION_TYPE.MESSAGE
  ) {
    return NOTIFICATION_SECTION.EXECUTION_UPDATES;
  }

  // Applications - hiring related
  if (
    type === NOTIFICATION_TYPE.APPLICATION ||
    type === NOTIFICATION_TYPE.INVITATION ||
    type === NOTIFICATION_TYPE.HIRE ||
    type === NOTIFICATION_TYPE.REJECTION ||
    type === NOTIFICATION_TYPE.APPLICANT_WITHDREW
  ) {
    return NOTIFICATION_SECTION.APPLICATIONS;
  }

  // Other Updates - everything else
  return NOTIFICATION_SECTION.OTHER_UPDATES;
}

export function getActionRequiredPriority(type) {
  const priorityMap = {
    [NOTIFICATION_TYPE.ESCROW_FUNDING_FAILED]: 1,
    [NOTIFICATION_TYPE.REFUND_CHARGEBACK]: 2,
    [NOTIFICATION_TYPE.DELIVERABLE_OVERDUE]: 3,
    [NOTIFICATION_TYPE.DRAFT_WAITING_REVIEW]: 4,
    [NOTIFICATION_TYPE.REVISION_WAITING_REVIEW]: 5,
    [NOTIFICATION_TYPE.PUBLISH_PROOF_WAITING_VERIFICATION]: 6,
    [NOTIFICATION_TYPE.READY_TO_COMPLETE]: 7,
    [NOTIFICATION_TYPE.APPLICATION_DEADLINE_APPROACHING]: 8,
  };

  return priorityMap[type] || 999;
}

